# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd01257dfe2f73bee895e0b02385ff1a16e8fda6c6162856c9e3b79ba69a7b158c8b9eaf1b2ab85b797ae41d7e1f163f330b4c5f5b11750c723f2ae37bd920f5

test:
  secret_key_base: 51ed6ffb206f836474794bdf4b66643f2f20b9084ab723b60c92e970c20a087d7457bd4a3050977a8054b52a24478846ea71b1f5e9efc387d782d69bd5b62fa0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
